// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheJourney.Api.Infrastructure.Database;

#nullable disable

namespace TheJourney.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117070326_AddCareerFramework")]
    partial class AddCareerFramework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.Auth.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.Auth.Models.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("Email");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("JobRoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("JobRoleId", "Version")
                        .IsUnique();

                    b.ToTable("AssessmentTemplates");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RequiredProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.1m);

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("AssessmentTemplateId", "SkillId")
                        .IsUnique();

                    b.ToTable("AssessmentTemplateSkills");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkillTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("AssessmentTemplateSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TrainingResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTemplateId");

                    b.HasIndex("TrainingResourceId");

                    b.HasIndex("AssessmentTemplateSkillId", "TrainingResourceId")
                        .IsUnique();

                    b.ToTable("AssessmentTemplateSkillTrainings");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredQualification")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TasksResponsibilities")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ToolsUsed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("MajorId");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.MajorIndustryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("MajorId", "IndustryId")
                        .IsUnique();

                    b.ToTable("MajorIndustryMappings");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.RoleSpecificQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTemplateId");

                    b.ToTable("RoleSpecificQuestions");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.TrainingResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TrainingResources");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.AssessmentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RoleSpecificQuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentAssessmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleSpecificQuestionId");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentAssessmentId");

                    b.ToTable("AssessmentAnswers");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FitScore")
                        .HasColumnType("numeric");

                    b.Property<string>("FitScoreBreakdownJson")
                        .HasColumnType("text");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTemplateId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAssessments");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCvs");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Auth.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Auth.Models.StudentPasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPasswordResetTokens");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Auth.Models.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTarget")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Purpose");

                    b.HasIndex("StudentId", "Channel", "Purpose");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.Auth.Models.LoginAttempt", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.Auth.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.Auth.Models.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId");

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.JobRole", "JobRole")
                        .WithMany("AssessmentTemplates")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkill", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", "AssessmentTemplate")
                        .WithMany("SkillMatrix")
                        .HasForeignKey("AssessmentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Skill", "Skill")
                        .WithMany("TemplateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentTemplate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkillTraining", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", null)
                        .WithMany("TrainingMappings")
                        .HasForeignKey("AssessmentTemplateId");

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkill", "AssessmentTemplateSkill")
                        .WithMany("TrainingRecommendations")
                        .HasForeignKey("AssessmentTemplateSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.TrainingResource", "TrainingResource")
                        .WithMany("TrainingMappings")
                        .HasForeignKey("TrainingResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentTemplateSkill");

                    b.Navigation("TrainingResource");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Industry", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.Auth.Models.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.JobRole", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.Auth.Models.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId");

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Major", "Major")
                        .WithMany("JobRoles")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Major", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.Auth.Models.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId");

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Industry", "Industry")
                        .WithMany("Majors")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.MajorIndustryMapping", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Major", "Major")
                        .WithMany("SuggestedIndustries")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.RoleSpecificQuestion", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", "AssessmentTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentTemplate");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.AssessmentAnswer", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.RoleSpecificQuestion", "RoleSpecificQuestion")
                        .WithMany()
                        .HasForeignKey("RoleSpecificQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentAssessment", "StudentAssessment")
                        .WithMany("Answers")
                        .HasForeignKey("StudentAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleSpecificQuestion");

                    b.Navigation("Skill");

                    b.Navigation("StudentAssessment");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentAssessment", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", "AssessmentTemplate")
                        .WithMany()
                        .HasForeignKey("AssessmentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheJourney.Api.Modules.Admin.CareerFramework.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheJourney.Api.Modules.Mobile.Auth.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentTemplate");

                    b.Navigation("JobRole");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentCv", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Mobile.Auth.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Auth.Models.StudentPasswordResetToken", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Mobile.Auth.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Auth.Models.VerificationCode", b =>
                {
                    b.HasOne("TheJourney.Api.Modules.Mobile.Auth.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplate", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SkillMatrix");

                    b.Navigation("TrainingMappings");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.AssessmentTemplateSkill", b =>
                {
                    b.Navigation("TrainingRecommendations");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Industry", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.JobRole", b =>
                {
                    b.Navigation("AssessmentTemplates");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Major", b =>
                {
                    b.Navigation("JobRoles");

                    b.Navigation("SuggestedIndustries");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.Skill", b =>
                {
                    b.Navigation("TemplateSkills");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Admin.CareerFramework.Models.TrainingResource", b =>
                {
                    b.Navigation("TrainingMappings");
                });

            modelBuilder.Entity("TheJourney.Api.Modules.Mobile.Assessment.Models.StudentAssessment", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
